name: FRU TOOLS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build FRU TOOLS
        run: |
          echo "Running 'make' command ..."
          make
